In [2]:
#Importamos Librerías
import pandas as pd                             # Importamos Pandas
from datetime import datetime                   # Iportar datetime

In [3]:
# Diagnósticos asignados por el hospital, codificados mediante el International Statistical Classification of Diseases DNA Related Health Problems (ICD)
DIAGNOSES_ICD= pd.read_csv('PF_UCI-/datasets/DIAGNOSES_ICD.csv')

# Grupos relacionados por el diagnóstico, que el hospital utiliza para facturación
DRGCODES= pd.read_csv('PF_UCI-/datasets/DRGCODES.csv')

# Exámenes de laboratorio para pacientes del hospital y para consultas externas
LABEVENTS= pd.read_csv('PF_UCI-/datasets/LABEVENTS.csv')

# Medidas y estudios microbiológicos de la base de datos del hospital
MICROBIOLOGYEVENTS= pd.read_csv('PF_UCI-/datasets/MICROBIOLOGYEVENTS.csv')

# Órdenes de medicamentos, no siempre administradas, para un paciente
PRESCRIPTIONS= pd.read_csv('PF_UCI-/datasets/PRESCRIPTIONS.csv')

DIAGNOSES_ICD

In [9]:
# Extraemos los nombres ombres de columnas en una lista
DIAGNOSES_ICD_NAMES = list(DIAGNOSES_ICD.columns.values)
# Descripcion de columnas
DIAGNOSES_ICD_DESCRIPCIÓN = ['Identificador de fila único','ID del Paciente','Id de Admisiones','Prioridad del código. La secuencia 1 es el código principal','Clasificación Internacional de Enfermedades']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
DIAGNOSES_ICD_ND= dict(zip(DIAGNOSES_ICD_NAMES,DIAGNOSES_ICD_DESCRIPCIÓN))
# Creamos el df
DIAGNOSES_ICD_columnas = pd.DataFrame([[key, DIAGNOSES_ICD_ND[key]] for key in DIAGNOSES_ICD_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
DIAGNOSES_ICD_dtype = ['INT','INT','INT','INT','VARCHAR(10)']
# Agregamos el tipo de dato
DIAGNOSES_ICD_columnas['Dtype'] = DIAGNOSES_ICD_dtype
# Agregamos nombre de columna
DIAGNOSES_ICD_columnas['tabla'] = 'DIAGNOSES_ICD'
#Print el resultado
DIAGNOSES_ICD_columnas

,Name,Descripcion,Dtype,tabla
0,row_id,Identificador de fila único,INT,DIAGNOSES_ICD
1,subject_id,ID del Paciente,INT,DIAGNOSES_ICD
2,hadm_id,Id de Admisiones,INT,DIAGNOSES_ICD
3,seq_num,Prioridad del código. La secuencia 1 es el cód...,INT,DIAGNOSES_ICD
4,icd9_code,Clasificación Internacional de Enfermedades,VARCHAR(10),DIAGNOSES_ICD

DRGCODES

In [16]:
# Extraemos los nombres ombres de columnas en una lista
DRGCODES_NAMES = list(DRGCODES.columns.values)
# Descripcion de columnas
DRGCODES_DESCRIPCIÓN = ['Identificador de la Fila',
                        'ID del Paciente',
                        'Id de Admisiones',
                        'Tipo de grupo relacionado con el diagnóstico',
                        'Código de grupo relacionado con el diagnóstico',
                        'Descripción del DRG',
                        'Gravedad relativa',
                        'Mortalidad relativa']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
DRGCODES_ND= dict(zip(DRGCODES_NAMES,DRGCODES_DESCRIPCIÓN))
# Creamos el df
DRGCODES_columnas = pd.DataFrame([[key, DRGCODES_ND[key]] for key in DRGCODES_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
DRGCODES_dtype = ['INT','INT','INT','VARCHAR(20)','VARCHAR(20)','VARCHAR(300)','SMALLINT','SMALLINT']
# Agregamos el tipo de dato
DRGCODES_columnas['Dtype'] = DRGCODES_dtype
# Agregamos nombre de columna
DRGCODES_columnas['tabla'] = 'DRGCODES'
#Print el resultado
DRGCODES_columnas

,Name,Descripcion,Dtype,tabla
0,row_id,Identificador de la Fila,INT,DRGCODES
1,subject_id,ID del Paciente,INT,DRGCODES
2,hadm_id,Id de Admisiones,INT,DRGCODES
3,drg_type,Tipo de grupo relacionado con el diagnóstico,VARCHAR(20),DRGCODES
4,drg_code,Código de grupo relacionado con el diagnóstico,VARCHAR(20),DRGCODES
5,description,Descripción del DRG,VARCHAR(300),DRGCODES
6,drg_severity,Gravedad relativa,SMALLINT,DRGCODES
7,drg_mortality,Mortalidad relativa,SMALLINT,DRGCODES

LABEVENTS

In [17]:
LABEVENTS.columns

Index(['row_id', 'subject_id', 'hadm_id', 'itemid', 'charttime', 'value',
       'valuenum', 'valueuom', 'flag'],
      dtype='object')

In [19]:
# Extraemos los nombres ombres de columnas en una lista
LABEVENTS_NAMES = list(LABEVENTS.columns.values)
# Descripcion de columnas
LABEVENTS_DESCRIPCIÓN = ['Identificador de fila único',
                         'ID del Paciente',
                         'Id de Admisiones',
                         'Referencia a la tabla D_LABITEMS',
                         'Momento en que ocurrió el evento',
                         'Valor del evento en formato texto',
                         'Valor del evento como un número',
                         'Unidad de medida',
                         'Estado del valor de la prueba de laboratorio (NULL = normal)']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
LABEVENTS_ND= dict(zip(LABEVENTS_NAMES,LABEVENTS_DESCRIPCIÓN))
# Creamos el df
LABEVENTS_columnas = pd.DataFrame([[key, LABEVENTS_ND[key]] for key in LABEVENTS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
LABEVENTS_dtype = ['INT','INT','INT','INT','TIMESTAMP(0)','VARCHAR(200)','DOUBLE PRECISION','VARCHAR(20)','VARCHAR(20)']
# Agregamos el tipo de dato
LABEVENTS_columnas['Dtype'] = LABEVENTS_dtype
# Agregamos nombre de columna
LABEVENTS_columnas['tabla'] = 'DIAGNOSES_ICD'
#Print el resultado
LABEVENTS_columnas

,Name,Descripcion,Dtype,tabla
0,row_id,Identificador de fila único,INT,DIAGNOSES_ICD
1,subject_id,ID del Paciente,INT,DIAGNOSES_ICD
2,hadm_id,Id de Admisiones,INT,DIAGNOSES_ICD
3,itemid,Referencia a la tabla D_LABITEMS,INT,DIAGNOSES_ICD
4,charttime,Momento en que ocurrió el evento,TIMESTAMP(0),DIAGNOSES_ICD
5,value,Valor del evento en formato texto,VARCHAR(200),DIAGNOSES_ICD
6,valuenum,Valor del evento como un número,DOUBLE PRECISION,DIAGNOSES_ICD
7,valueuom,Unidad de medida,VARCHAR(20),DIAGNOSES_ICD
8,flag,Estado del valor de la prueba de laboratorio (...,VARCHAR(20),DIAGNOSES_ICD

MICROBIOLOGYEVENTS

In [20]:
MICROBIOLOGYEVENTS.columns

Index(['row_id', 'subject_id', 'hadm_id', 'chartdate', 'charttime',
       'spec_itemid', 'spec_type_desc', 'org_itemid', 'org_name',
       'isolate_num', 'ab_itemid', 'ab_name', 'dilution_text',
       'dilution_comparison', 'dilution_value', 'interpretation'],
      dtype='object')

In [21]:
# Extraemos los nombres ombres de columnas en una lista
MICROBIOLOGYEVENTS_NAMES = list(MICROBIOLOGYEVENTS.columns.values)
# Descripcion de columnas
MICROBIOLOGYEVENTS_DESCRIPCIÓN = ['Identificador de fila único',
                                  'ID del Paciente',
                                  'Id de Admisiones',
                                  'Fecha en que ocurrió el evento',
                                  'Hora en que ocurrió el evento',
                                  'Identifica el espécimen',
                                  'Descripción del espécimen',
                                  'Identifica el organismo',
                                  'Nombre del organismo',
                                  'Número aislado asociado a la prueba',
                                  'Identifica el anticuerpo',
                                  'Nombre del anticuerpo utilizado',
                                  'La cantidad de dilución probada y la comparación que se hizo',
                                  'El componente de comparación de DILUTION_TEXT',
                                  'El valor del componente DILUTION_TEXT',
                                  'Interpretación de la prueba']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
MICROBIOLOGYEVENTS_ND= dict(zip(MICROBIOLOGYEVENTS_NAMES,MICROBIOLOGYEVENTS_DESCRIPCIÓN))
# Creamos el df
MICROBIOLOGYEVENTS_columnas = pd.DataFrame([[key, MICROBIOLOGYEVENTS_ND[key]] for key in MICROBIOLOGYEVENTS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
MICROBIOLOGYEVENTS_dtype = ['INT','INT','INT','TIMESTAMP(0)','TIMESTAMP(0)','INT','VARCHAR(100)',
                            'INT','VARCHAR(100)','SMALLINT','INT','VARCHAR(30)','VARCHAR(10)',
                            'VARCHAR(20)','DOUBLE PRECISION','VARCHAR(5)']
# Agregamos el tipo de dato
MICROBIOLOGYEVENTS_columnas['Dtype'] = MICROBIOLOGYEVENTS_dtype
# Agregamos nombre de columna
MICROBIOLOGYEVENTS_columnas['tabla'] = 'MICROBIOLOGYEVENTS'
#Print el resultado
MICROBIOLOGYEVENTS_columnas

,Name,Descripcion,Dtype,tabla
0,row_id,Identificador de fila único,INT,MICROBIOLOGYEVENTS
1,subject_id,ID del Paciente,INT,MICROBIOLOGYEVENTS
2,hadm_id,Id de Admisiones,INT,MICROBIOLOGYEVENTS
3,chartdate,Fecha en que ocurrió el evento,TIMESTAMP(0),MICROBIOLOGYEVENTS
4,charttime,Hora en que ocurrió el evento,TIMESTAMP(0),MICROBIOLOGYEVENTS
5,spec_itemid,Identifica el espécimen,INT,MICROBIOLOGYEVENTS
6,spec_type_desc,Descripción del espécimen,VARCHAR(100),MICROBIOLOGYEVENTS
7,org_itemid,Identifica el organismo,INT,MICROBIOLOGYEVENTS
8,org_name,Nombre del organismo,VARCHAR(100),MICROBIOLOGYEVENTS
9,isolate_num,Número aislado asociado a la prueba,SMALLINT,MICROBIOLOGYEVENTS
10,ab_itemid,Identifica el anticuerpo,INT,MICROBIOLOGYEVENTS
11,ab_name,Nombre del anticuerpo utilizado,VARCHAR(30),MICROBIOLOGYEVENTS
12,dilution_text,La cantidad de dilución probada y la comparaci...,VARCHAR(10),MICROBIOLOGYEVENTS
13,dilution_comparison,El componente de comparación de DILUTION_TEXT,VARCHAR(20),MICROBIOLOGYEVENTS
14,dilution_value,El valor del componente DILUTION_TEXT,DOUBLE PRECISION,MICROBIOLOGYEVENTS
15,interpretation,Interpretación de la prueba,VARCHAR(5),MICROBIOLOGYEVENTS

PRESCRIPTIONS

In [22]:
PRESCRIPTIONS.columns

Index(['row_id', 'subject_id', 'hadm_id', 'icustay_id', 'startdate', 'enddate',
       'drug_type', 'drug', 'drug_name_poe', 'drug_name_generic',
       'formulary_drug_cd', 'gsn', 'ndc', 'prod_strength', 'dose_val_rx',
       'dose_unit_rx', 'form_val_disp', 'form_unit_disp', 'route'],
      dtype='object')

In [24]:
# Extraemos los nombres ombres de columnas en una lista
PRESCRIPTIONS_NAMES = list(PRESCRIPTIONS.columns.values)
# Descripcion de columnas
PRESCRIPTIONS_DESCRIPCIÓN = ['Identificador de fila único',
                             'ID del Paciente',
                             'ID del Admisiones',
                             'Referencia a ICUSTAYS',
                             'Fecha en que comenzó la prescripción',
                             'Fecha en que terminó la prescripción',
                             'tipo de droga',
                             'nombre de la droga',
                             'Nombre del medicamento en la interfaz de entrada de pedidos del proveedor',
                             'nombre genérico de la droga',
                             'Código de medicamento del formulario',
                             'Número de secuencia genérico',
                             'Código Nacional de Drogas',
                             'Fuerza de la droga (producto)',
                             'Dosis del fármaco prescrito',
                             'Unidad de medida asociada a la dosis',
                             'Cantidad de la fórmula dispensada',
                             'Unidad de medida asociada a la formulación',
                             'Vía de administración']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
PRESCRIPTIONS_ND= dict(zip(PRESCRIPTIONS_NAMES,PRESCRIPTIONS_DESCRIPCIÓN))
# Creamos el df
PRESCRIPTIONS_columnas = pd.DataFrame([[key, PRESCRIPTIONS_ND[key]] for key in PRESCRIPTIONS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
PRESCRIPTIONS_dtype = ['INT','INT','INT','INT','TIMESTAMP(0)','TIMESTAMP(0)','VARCHAR(100)',
                       'VARCHAR(100)','VARCHAR(100)','VARCHAR(100)','VARCHAR(120)','VARCHAR(200)',
                       'VARCHAR(120)','VARCHAR(120)','VARCHAR(120)','VARCHAR(120)','VARCHAR(120)',
                       'VARCHAR(120)','VARCHAR(120)']
# Agregamos el tipo de dato
PRESCRIPTIONS_columnas['Dtype'] = PRESCRIPTIONS_dtype
# Agregamos nombre de columna
PRESCRIPTIONS_columnas['tabla'] = 'PRESCRIPTIONS'
#Print el resultado
PRESCRIPTIONS_columnas

,Name,Descripcion,Dtype,tabla
0,row_id,Identificador de fila único,INT,PRESCRIPTIONS
1,subject_id,ID del Paciente,INT,PRESCRIPTIONS
2,hadm_id,ID del Admisiones,INT,PRESCRIPTIONS
3,icustay_id,Referencia a ICUSTAYS,INT,PRESCRIPTIONS
4,startdate,Fecha en que comenzó la prescripción,TIMESTAMP(0),PRESCRIPTIONS
5,enddate,Fecha en que terminó la prescripción,TIMESTAMP(0),PRESCRIPTIONS
6,drug_type,tipo de droga,VARCHAR(100),PRESCRIPTIONS
7,drug,nombre de la droga,VARCHAR(100),PRESCRIPTIONS
8,drug_name_poe,Nombre del medicamento en la interfaz de entra...,VARCHAR(100),PRESCRIPTIONS
9,drug_name_generic,nombre genérico de la droga,VARCHAR(100),PRESCRIPTIONS
10,formulary_drug_cd,Código de medicamento del formulario,VARCHAR(120),PRESCRIPTIONS
11,gsn,Número de secuencia genérico,VARCHAR(200),PRESCRIPTIONS
12,ndc,Código Nacional de Drogas,VARCHAR(120),PRESCRIPTIONS
13,prod_strength,Fuerza de la droga (producto),VARCHAR(120),PRESCRIPTIONS
14,dose_val_rx,Dosis del fármaco prescrito,VARCHAR(120),PRESCRIPTIONS
15,dose_unit_rx,Unidad de medida asociada a la dosis,VARCHAR(120),PRESCRIPTIONS
16,form_val_disp,Cantidad de la fórmula dispensada,VARCHAR(120),PRESCRIPTIONS
17,form_unit_disp,Unidad de medida asociada a la formulación,VARCHAR(120),PRESCRIPTIONS
18,route,Vía de administración,VARCHAR(120),PRESCRIPTIONS