In [1]:
#Importamos Librerías
import pandas as pd     
from datetime import datetime

In [2]:
# Diagnósticos asignados por el hospital, codificados mediante el International Statistical Classification of Diseases DNA Related Health Problems (ICD)
DIAGNOSES_ICD= pd.read_csv('PF_UCI-/datasets/DIAGNOSES_ICD.csv')

# Grupos relacionados por el diagnóstico, que el hospital utiliza para facturación
DRGCODES= pd.read_csv('PF_UCI-/datasets/DRGCODES.csv')

# Exámenes de laboratorio para pacientes del hospital y para consultas externas
LABEVENTS= pd.read_csv('PF_UCI-/datasets/LABEVENTS.csv')

# Medidas y estudios microbiológicos de la base de datos del hospital
MICROBIOLOGYEVENTS= pd.read_csv('PF_UCI-/datasets/MICROBIOLOGYEVENTS.csv')

# Órdenes de medicamentos, no siempre administradas, para un paciente
PRESCRIPTIONS= pd.read_csv('PF_UCI-/datasets/PRESCRIPTIONS.csv')

DIAGNOSES_ICD

In [3]:
# Extraemos los nombres ombres de columnas en una lista
DIAGNOSES_ICD_NAMES = list(DIAGNOSES_ICD.columns.values)
# Descripcion de columnas
DIAGNOSES_ICD_DESCRIPCIÓN = ['Identificador de fila único','ID del Paciente','Id de Admisiones','Prioridad del código. La secuencia 1 es el código principal','Clasificación Internacional de Enfermedades']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
DIAGNOSES_ICD_ND= dict(zip(DIAGNOSES_ICD_NAMES,DIAGNOSES_ICD_DESCRIPCIÓN))
# Creamos el df
DIAGNOSES_ICD_columnas = pd.DataFrame([[key, DIAGNOSES_ICD_ND[key]] for key in DIAGNOSES_ICD_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
DIAGNOSES_ICD_dtype = ['INT','INT','INT','INT','VARCHAR(10)']
# Agregamos el tipo de dato
DIAGNOSES_ICD_columnas['Dtype'] = DIAGNOSES_ICD_dtype
# --------------------
# PK
DIAGNOSES_ICD_PK=['Y','','','','']
# FK
DIAGNOSES_ICD_FK=['','Y','Y','','Y']
# Agregamos el PK
DIAGNOSES_ICD_columnas['PK']=DIAGNOSES_ICD_PK
# Agregamos el FK
DIAGNOSES_ICD_columnas['FK']=DIAGNOSES_ICD_FK
# -------------------------
# Agregamos nombre de columna
DIAGNOSES_ICD_columnas['tabla'] = 'DIAGNOSES_ICD'
# Agregamos número de columna
DIAGNOSES_ICD_columnas['n tabla'] = 16
#Print el resultado
DIAGNOSES_ICD_columnas

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de fila único,INT,Y,,DIAGNOSES_ICD,16
1,subject_id,ID del Paciente,INT,,Y,DIAGNOSES_ICD,16
2,hadm_id,Id de Admisiones,INT,,Y,DIAGNOSES_ICD,16
3,seq_num,Prioridad del código. La secuencia 1 es el cód...,INT,,,DIAGNOSES_ICD,16
4,icd9_code,Clasificación Internacional de Enfermedades,VARCHAR(10),,Y,DIAGNOSES_ICD,16

DRGCODES

In [4]:
# Extraemos los nombres ombres de columnas en una lista
DRGCODES_NAMES = list(DRGCODES.columns.values)
# Descripcion de columnas
DRGCODES_DESCRIPCIÓN = ['Identificador de la Fila',
                        'ID del Paciente',
                        'Id de Admisiones',
                        'Tipo de grupo relacionado con el diagnóstico',
                        'Código de grupo relacionado con el diagnóstico',
                        'Descripción del DRG',
                        'Gravedad relativa',
                        'Mortalidad relativa']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
DRGCODES_ND= dict(zip(DRGCODES_NAMES,DRGCODES_DESCRIPCIÓN))
# Creamos el df
DRGCODES_columnas = pd.DataFrame([[key, DRGCODES_ND[key]] for key in DRGCODES_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
DRGCODES_dtype = ['INT','INT','INT','VARCHAR(20)','VARCHAR(20)','VARCHAR(300)','SMALLINT','SMALLINT']
# Agregamos el tipo de dato
DRGCODES_columnas['Dtype'] = DRGCODES_dtype
# --------------------
# PK
DRGCODES_PK=['','','','','Y','','','']
# FK
DRGCODES_FK=['','Y','Y','','','','','']
# Agregamos el PK
DRGCODES_columnas['PK']=DRGCODES_PK
# Agregamos el FK
DRGCODES_columnas['FK']=DRGCODES_FK
# -------------------------
# Agregamos nombre de columna
DRGCODES_columnas['tabla'] = 'DRGCODES'
# Agregamos número de columna
DRGCODES_columnas['n tabla'] = 17
#Print el resultado
DRGCODES_columnas

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de la Fila,INT,,,DRGCODES,17
1,subject_id,ID del Paciente,INT,,Y,DRGCODES,17
2,hadm_id,Id de Admisiones,INT,,Y,DRGCODES,17
3,drg_type,Tipo de grupo relacionado con el diagnóstico,VARCHAR(20),,,DRGCODES,17
4,drg_code,Código de grupo relacionado con el diagnóstico,VARCHAR(20),Y,,DRGCODES,17
5,description,Descripción del DRG,VARCHAR(300),,,DRGCODES,17
6,drg_severity,Gravedad relativa,SMALLINT,,,DRGCODES,17
7,drg_mortality,Mortalidad relativa,SMALLINT,,,DRGCODES,17

LABEVENTS

In [5]:
# Extraemos los nombres ombres de columnas en una lista
LABEVENTS_NAMES = list(LABEVENTS.columns.values)
# Descripcion de columnas
LABEVENTS_DESCRIPCIÓN = ['Identificador de fila único',
                         'ID del Paciente',
                         'Id de Admisiones',
                         'Referencia a la tabla D_LABITEMS',
                         'Momento en que ocurrió el evento',
                         'Valor del evento en formato texto',
                         'Valor del evento como un número',
                         'Unidad de medida',
                         'Estado del valor de la prueba de laboratorio (NULL = normal)']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
LABEVENTS_ND= dict(zip(LABEVENTS_NAMES,LABEVENTS_DESCRIPCIÓN))
# Creamos el df
LABEVENTS_columnas = pd.DataFrame([[key, LABEVENTS_ND[key]] for key in LABEVENTS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
LABEVENTS_dtype = ['INT','INT','INT','INT','TIMESTAMP(0)','VARCHAR(200)','DOUBLE PRECISION','VARCHAR(20)','VARCHAR(20)']
# Agregamos el tipo de dato
LABEVENTS_columnas['Dtype'] = LABEVENTS_dtype
# --------------------
# PK
LABEVENTS_PK=['Y','','','','','','','','']
# FK
LABEVENTS_FK=['','Y','Y','Y','','','','','']
# Agregamos el PK
LABEVENTS_columnas['PK']=LABEVENTS_PK
# Agregamos el FK
LABEVENTS_columnas['FK']=LABEVENTS_FK
# -------------------------
# Agregamos nombre de columna
LABEVENTS_columnas['tabla'] = 'DIAGNOSES_ICD'
# Agregamos número de columna
LABEVENTS_columnas['n tabla'] = 18
#Print el resultado
LABEVENTS_columnas

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de fila único,INT,Y,,DIAGNOSES_ICD,18
1,subject_id,ID del Paciente,INT,,Y,DIAGNOSES_ICD,18
2,hadm_id,Id de Admisiones,INT,,Y,DIAGNOSES_ICD,18
3,itemid,Referencia a la tabla D_LABITEMS,INT,,Y,DIAGNOSES_ICD,18
4,charttime,Momento en que ocurrió el evento,TIMESTAMP(0),,,DIAGNOSES_ICD,18
5,value,Valor del evento en formato texto,VARCHAR(200),,,DIAGNOSES_ICD,18
6,valuenum,Valor del evento como un número,DOUBLE PRECISION,,,DIAGNOSES_ICD,18
7,valueuom,Unidad de medida,VARCHAR(20),,,DIAGNOSES_ICD,18
8,flag,Estado del valor de la prueba de laboratorio (...,VARCHAR(20),,,DIAGNOSES_ICD,18

MICROBIOLOGYEVENTS

In [6]:
# Extraemos los nombres ombres de columnas en una lista
MICROBIOLOGYEVENTS_NAMES = list(MICROBIOLOGYEVENTS.columns.values)
# Descripcion de columnas
MICROBIOLOGYEVENTS_DESCRIPCIÓN = ['Identificador de fila único',
                                  'ID del Paciente',
                                  'Id de Admisiones',
                                  'Fecha en que ocurrió el evento',
                                  'Hora en que ocurrió el evento',
                                  'Identifica el espécimen',
                                  'Descripción del espécimen',
                                  'Identifica el organismo',
                                  'Nombre del organismo',
                                  'Número aislado asociado a la prueba',
                                  'Identifica el anticuerpo',
                                  'Nombre del anticuerpo utilizado',
                                  'La cantidad de dilución probada y la comparación que se hizo',
                                  'El componente de comparación de DILUTION_TEXT',
                                  'El valor del componente DILUTION_TEXT',
                                  'Interpretación de la prueba']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
MICROBIOLOGYEVENTS_ND= dict(zip(MICROBIOLOGYEVENTS_NAMES,MICROBIOLOGYEVENTS_DESCRIPCIÓN))
# Creamos el df
MICROBIOLOGYEVENTS_columnas = pd.DataFrame([[key, MICROBIOLOGYEVENTS_ND[key]] for key in MICROBIOLOGYEVENTS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
MICROBIOLOGYEVENTS_dtype = ['INT','INT','INT','TIMESTAMP(0)','TIMESTAMP(0)','INT','VARCHAR(100)',
                            'INT','VARCHAR(100)','SMALLINT','INT','VARCHAR(30)','VARCHAR(10)',
                            'VARCHAR(20)','DOUBLE PRECISION','VARCHAR(5)']
# Agregamos el tipo de dato
MICROBIOLOGYEVENTS_columnas['Dtype'] = MICROBIOLOGYEVENTS_dtype
# --------------------
# PK
MICROBIOLOGYEVENTS_PK=['Y','','','','','','','','','','','','','','','']
# FK
MICROBIOLOGYEVENTS_FK=['','Y','Y','','','Y','','Y','','','Y','','','','','']
# Agregamos el PK
MICROBIOLOGYEVENTS_columnas['PK']=MICROBIOLOGYEVENTS_PK
# Agregamos el FK
MICROBIOLOGYEVENTS_columnas['FK']=MICROBIOLOGYEVENTS_FK
# -------------------------
# Agregamos nombre de columna
MICROBIOLOGYEVENTS_columnas['tabla'] = 'MICROBIOLOGYEVENTS'
# Agregamos número de columna
MICROBIOLOGYEVENTS_columnas['n tabla'] = 19
#Print el resultado
MICROBIOLOGYEVENTS_columnas

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de fila único,INT,Y,,MICROBIOLOGYEVENTS,19
1,subject_id,ID del Paciente,INT,,Y,MICROBIOLOGYEVENTS,19
2,hadm_id,Id de Admisiones,INT,,Y,MICROBIOLOGYEVENTS,19
3,chartdate,Fecha en que ocurrió el evento,TIMESTAMP(0),,,MICROBIOLOGYEVENTS,19
4,charttime,Hora en que ocurrió el evento,TIMESTAMP(0),,,MICROBIOLOGYEVENTS,19
5,spec_itemid,Identifica el espécimen,INT,,Y,MICROBIOLOGYEVENTS,19
6,spec_type_desc,Descripción del espécimen,VARCHAR(100),,,MICROBIOLOGYEVENTS,19
7,org_itemid,Identifica el organismo,INT,,Y,MICROBIOLOGYEVENTS,19
8,org_name,Nombre del organismo,VARCHAR(100),,,MICROBIOLOGYEVENTS,19
9,isolate_num,Número aislado asociado a la prueba,SMALLINT,,,MICROBIOLOGYEVENTS,19
10,ab_itemid,Identifica el anticuerpo,INT,,Y,MICROBIOLOGYEVENTS,19
11,ab_name,Nombre del anticuerpo utilizado,VARCHAR(30),,,MICROBIOLOGYEVENTS,19
12,dilution_text,La cantidad de dilución probada y la comparaci...,VARCHAR(10),,,MICROBIOLOGYEVENTS,19
13,dilution_comparison,El componente de comparación de DILUTION_TEXT,VARCHAR(20),,,MICROBIOLOGYEVENTS,19
14,dilution_value,El valor del componente DILUTION_TEXT,DOUBLE PRECISION,,,MICROBIOLOGYEVENTS,19
15,interpretation,Interpretación de la prueba,VARCHAR(5),,,MICROBIOLOGYEVENTS,19

PRESCRIPTIONS

In [7]:
# Extraemos los nombres ombres de columnas en una lista
PRESCRIPTIONS_NAMES = list(PRESCRIPTIONS.columns.values)
# Descripcion de columnas
PRESCRIPTIONS_DESCRIPCIÓN = ['Identificador de fila único',
                             'ID del Paciente',
                             'ID del Admisiones',
                             'Referencia a ICUSTAYS',
                             'Fecha en que comenzó la prescripción',
                             'Fecha en que terminó la prescripción',
                             'tipo de droga',
                             'nombre de la droga',
                             'Nombre del medicamento en la interfaz de entrada de pedidos del proveedor',
                             'nombre genérico de la droga',
                             'Código de medicamento del formulario',
                             'Número de secuencia genérico',
                             'Código Nacional de Drogas',
                             'Fuerza de la droga (producto)',
                             'Dosis del fármaco prescrito',
                             'Unidad de medida asociada a la dosis',
                             'Cantidad de la fórmula dispensada',
                             'Unidad de medida asociada a la formulación',
                             'Vía de administración']
# Unimos la lista con nombres de columnas y la descripcion de cada columna
PRESCRIPTIONS_ND= dict(zip(PRESCRIPTIONS_NAMES,PRESCRIPTIONS_DESCRIPCIÓN))
# Creamos el df
PRESCRIPTIONS_columnas = pd.DataFrame([[key, PRESCRIPTIONS_ND[key]] for key in PRESCRIPTIONS_ND.keys()], columns=['Name', 'Descripcion'])
# Tipo de dato de cada columna
PRESCRIPTIONS_dtype = ['INT','INT','INT','INT','TIMESTAMP(0)','TIMESTAMP(0)','VARCHAR(100)',
                       'VARCHAR(100)','VARCHAR(100)','VARCHAR(100)','VARCHAR(120)','VARCHAR(200)',
                       'VARCHAR(120)','VARCHAR(120)','VARCHAR(120)','VARCHAR(120)','VARCHAR(120)',
                       'VARCHAR(120)','VARCHAR(120)']
# Agregamos el tipo de dato
PRESCRIPTIONS_columnas['Dtype'] = PRESCRIPTIONS_dtype
# --------------------
# PK
PRESCRIPTIONS_PK=['Y','','','','','','','','','','','','','','','','','','']
# FK
PRESCRIPTIONS_FK=['','Y','Y','Y','','','','','','','','','','','','','','','']
# Agregamos el PK
PRESCRIPTIONS_columnas['PK']=PRESCRIPTIONS_PK
# Agregamos el FK
PRESCRIPTIONS_columnas['FK']=PRESCRIPTIONS_FK
# -------------------------
# Agregamos nombre de columna
PRESCRIPTIONS_columnas['tabla'] = 'PRESCRIPTIONS'
# Agregamos número de columna
PRESCRIPTIONS_columnas['n tabla'] = 20
#Print el resultado
PRESCRIPTIONS_columnas

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de fila único,INT,Y,,PRESCRIPTIONS,20
1,subject_id,ID del Paciente,INT,,Y,PRESCRIPTIONS,20
2,hadm_id,ID del Admisiones,INT,,Y,PRESCRIPTIONS,20
3,icustay_id,Referencia a ICUSTAYS,INT,,Y,PRESCRIPTIONS,20
4,startdate,Fecha en que comenzó la prescripción,TIMESTAMP(0),,,PRESCRIPTIONS,20
5,enddate,Fecha en que terminó la prescripción,TIMESTAMP(0),,,PRESCRIPTIONS,20
6,drug_type,tipo de droga,VARCHAR(100),,,PRESCRIPTIONS,20
7,drug,nombre de la droga,VARCHAR(100),,,PRESCRIPTIONS,20
8,drug_name_poe,Nombre del medicamento en la interfaz de entra...,VARCHAR(100),,,PRESCRIPTIONS,20
9,drug_name_generic,nombre genérico de la droga,VARCHAR(100),,,PRESCRIPTIONS,20
10,formulary_drug_cd,Código de medicamento del formulario,VARCHAR(120),,,PRESCRIPTIONS,20
11,gsn,Número de secuencia genérico,VARCHAR(200),,,PRESCRIPTIONS,20
12,ndc,Código Nacional de Drogas,VARCHAR(120),,,PRESCRIPTIONS,20
13,prod_strength,Fuerza de la droga (producto),VARCHAR(120),,,PRESCRIPTIONS,20
14,dose_val_rx,Dosis del fármaco prescrito,VARCHAR(120),,,PRESCRIPTIONS,20
15,dose_unit_rx,Unidad de medida asociada a la dosis,VARCHAR(120),,,PRESCRIPTIONS,20
16,form_val_disp,Cantidad de la fórmula dispensada,VARCHAR(120),,,PRESCRIPTIONS,20
17,form_unit_disp,Unidad de medida asociada a la formulación,VARCHAR(120),,,PRESCRIPTIONS,20
18,route,Vía de administración,VARCHAR(120),,,PRESCRIPTIONS,20

# TABLA UNIDA

In [8]:

tablas_16_20 = pd.concat([DIAGNOSES_ICD_columnas, DRGCODES_columnas,LABEVENTS_columnas,MICROBIOLOGYEVENTS_columnas,PRESCRIPTIONS_columnas],axis=0, ignore_index=True)
tablas_16_20.shape

(57, 7)

In [9]:
tablas_16_20.to_csv('ER_16_20.csv', index=False)

In [10]:
tablas_16_20

,Name,Descripcion,Dtype,PK,FK,tabla,n tabla
0,row_id,Identificador de fila único,INT,Y,,DIAGNOSES_ICD,16
1,subject_id,ID del Paciente,INT,,Y,DIAGNOSES_ICD,16
2,hadm_id,Id de Admisiones,INT,,Y,DIAGNOSES_ICD,16
3,seq_num,Prioridad del código. La secuencia 1 es el cód...,INT,,,DIAGNOSES_ICD,16
4,icd9_code,Clasificación Internacional de Enfermedades,VARCHAR(10),,Y,DIAGNOSES_ICD,16
5,row_id,Identificador de la Fila,INT,,,DRGCODES,17
6,subject_id,ID del Paciente,INT,,Y,DRGCODES,17
7,hadm_id,Id de Admisiones,INT,,Y,DRGCODES,17
8,drg_type,Tipo de grupo relacionado con el diagnóstico,VARCHAR(20),,,DRGCODES,17
9,drg_code,Código de grupo relacionado con el diagnóstico,VARCHAR(20),Y,,DRGCODES,17
10,description,Descripción del DRG,VARCHAR(300),,,DRGCODES,17
11,drg_severity,Gravedad relativa,SMALLINT,,,DRGCODES,17
12,drg_mortality,Mortalidad relativa,SMALLINT,,,DRGCODES,17
13,row_id,Identificador de fila único,INT,Y,,DIAGNOSES_ICD,18
14,subject_id,ID del Paciente,INT,,Y,DIAGNOSES_ICD,18
15,hadm_id,Id de Admisiones,INT,,Y,DIAGNOSES_ICD,18
16,itemid,Referencia a la tabla D_LABITEMS,INT,,Y,DIAGNOSES_ICD,18
17,charttime,Momento en que ocurrió el evento,TIMESTAMP(0),,,DIAGNOSES_ICD,18
18,value,Valor del evento en formato texto,VARCHAR(200),,,DIAGNOSES_ICD,18
19,valuenum,Valor del evento como un número,DOUBLE PRECISION,,,DIAGNOSES_ICD,18
20,valueuom,Unidad de medida,VARCHAR(20),,,DIAGNOSES_ICD,18
21,flag,Estado del valor de la prueba de laboratorio (...,VARCHAR(20),,,DIAGNOSES_ICD,18
22,row_id,Identificador de fila único,INT,Y,,MICROBIOLOGYEVENTS,19
23,subject_id,ID del Paciente,INT,,Y,MICROBIOLOGYEVENTS,19
24,hadm_id,Id de Admisiones,INT,,Y,MICROBIOLOGYEVENTS,19
25,chartdate,Fecha en que ocurrió el evento,TIMESTAMP(0),,,MICROBIOLOGYEVENTS,19
26,charttime,Hora en que ocurrió el evento,TIMESTAMP(0),,,MICROBIOLOGYEVENTS,19
27,spec_itemid,Identifica el espécimen,INT,,Y,MICROBIOLOGYEVENTS,19
28,spec_type_desc,Descripción del espécimen,VARCHAR(100),,,MICROBIOLOGYEVENTS,19
29,org_itemid,Identifica el organismo,INT,,Y,MICROBIOLOGYEVENTS,19
30,org_name,Nombre del organismo,VARCHAR(100),,,MICROBIOLOGYEVENTS,19
31,isolate_num,Número aislado asociado a la prueba,SMALLINT,,,MICROBIOLOGYEVENTS,19
32,ab_itemid,Identifica el anticuerpo,INT,,Y,MICROBIOLOGYEVENTS,19
33,ab_name,Nombre del anticuerpo utilizado,VARCHAR(30),,,MICROBIOLOGYEVENTS,19
34,dilution_text,La cantidad de dilución probada y la comparaci...,VARCHAR(10),,,MICROBIOLOGYEVENTS,19
35,dilution_comparison,El componente de comparación de DILUTION_TEXT,VARCHAR(20),,,MICROBIOLOGYEVENTS,19
36,dilution_value,El valor del componente DILUTION_TEXT,DOUBLE PRECISION,,,MICROBIOLOGYEVENTS,19
37,interpretation,Interpretación de la prueba,VARCHAR(5),,,MICROBIOLOGYEVENTS,19
38,row_id,Identificador de fila único,INT,Y,,PRESCRIPTIONS,20
39,subject_id,ID del Paciente,INT,,Y,PRESCRIPTIONS,20
40,hadm_id,ID del Admisiones,INT,,Y,PRESCRIPTIONS,20
41,icustay_id,Referencia a ICUSTAYS,INT,,Y,PRESCRIPTIONS,20
42,startdate,Fecha en que comenzó la prescripción,TIMESTAMP(0),,,PRESCRIPTIONS,20
43,enddate,Fecha en que terminó la prescripción,TIMESTAMP(0),,,PRESCRIPTIONS,20
44,drug_type,tipo de droga,VARCHAR(100),,,PRESCRIPTIONS,20
45,drug,nombre de la droga,VARCHAR(100),,,PRESCRIPTIONS,20
46,drug_name_poe,Nombre del medicamento en la interfaz de entra...,VARCHAR(100),,,PRESCRIPTIONS,20
47,drug_name_generic,nombre genérico de la droga,VARCHAR(100),,,PRESCRIPTIONS,20
48,formulary_drug_cd,Código de medicamento del formulario,VARCHAR(120),,,PRESCRIPTIONS,20
49,gsn,Número de secuencia genérico,VARCHAR(200),,,PRESCRIPTIONS,20
50,ndc,Código Nacional de Drogas,VARCHAR(120),,,PRESCRIPTIONS,20
51,prod_strength,Fuerza de la droga (producto),VARCHAR(120),,,PRESCRIPTIONS,20
52,dose_val_rx,Dosis del fármaco prescrito,VARCHAR(120),,,PRESCRIPTIONS,20
53,dose_unit_rx,Unidad de medida asociada a la dosis,VARCHAR(120),,,PRESCRIPTIONS,20
54,form_val_disp,Cantidad de la fórmula dispensada,VARCHAR(120),,,PRESCRIPTIONS,20
55,form_unit_disp,Unidad de medida asociada a la formulación,VARCHAR(120),,,PRESCRIPTIONS,20
56,route,Vía de administración,VARCHAR(120),,,PRESCRIPTIONS,20